version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: MyDb
      POSTGRES_USER: MyUser
      POSTGRES_PASSWORD: MyPassword
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
